# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java test
#test commit addional remove tag line task49
trigger:
- master

#test code move commit to wkitem preo zoom

pool:
  vmImage: windows-latest
  demands: maven

stages:
  - stage: 'Build'
    jobs:
    - job: 'Build1'
      steps:
      - task: ServiceNow-DevOps-Agent-Job-Notification@1
        inputs:
          connectedServiceName: 'wiprocoelabdev-AzureCoeLab-ServiceNow DevOps Service Connection'
          Phase: 'STARTED'
            
      - task: Maven@3
        inputs:
          mavenPomFile: 'pom.xml'
          mavenOptions: '-Xmx3072m'
          javaHomeOption: 'JDKVersion'
          jdkVersionOption: '1.8'
          jdkArchitectureOption: 'x64'
          publishJUnitResults: true
          testResultsFiles: '**/surefire-reports/TEST-*.xml'
          goals: 'package'

      # - task: Maven@4
      #   displayName: 'Maven pom.xml'

      - task: CopyFiles@2
        displayName: 'Copy Files to: $(Build.ArtifactStagingDirectory)'
        inputs:
          SourceFolder: '$(Build.SourcesDirectory)'
          Contents: |
            **/target/*.war
            *.sql
          TargetFolder: '$(Build.ArtifactStagingDirectory)'
      - task: PublishBuildArtifacts@1
        displayName: 'Publish Artifact: drop'
        
      - task: ServiceNow-DevOps-Agent-Job-Notification@1
        inputs:
          connectedServiceName: 'wiprocoelabdev-AzureCoeLab-ServiceNow DevOps Service Connection'
          Phase: 'COMPLETED'        
  # - stage: 'Test'
  #   jobs:
  #   - job: 'Test1'
  #     steps:
  #     - task: ServiceNow-DevOps-Agent-Job-Notification@1
  #       inputs:
  #         connectedServiceName: 'wiprocoelabdev-AzureCoeLab-ServiceNow DevOps Service Connection'
  #         Phase: 'STARTED'

  #     - task: ServiceNow-DevOps-Agent-Job-Notification@1
  #       inputs:
  #         connectedServiceName: 'wiprocoelabdev-AzureCoeLab-ServiceNow DevOps Service Connection'
  #         Phase: 'COMPLETED'

  - stage: 'Deploy'
    jobs:
      - job: 'ChangeRequest'
        pool: server 
        steps:
        - task: ServiceNow-DevOps-Server-Job-Notification@1
          inputs:
            connectedServiceName: 'wiprocoelabdev-AzureCoeLab-ServiceNow DevOps Service Connection'
            Phase: 'STARTED'
        - task: ServiceNow-DevOps-Server-Change-Acceleration@1
          inputs:
            connectedServiceName: 'wiprocoelabdev-AzureCoeLab-ServiceNow DevOps Service Connection'
            Upstreamjob: 'Test'
      #   # - task: TomcatDeployment@1
      #   #   inputs:
      #   #     TomcatUrl: 'http://localhost:8080'
      #   #     Username: 'tommgr'
      #   #     Password: 'Tom123456'
      #   #     Warfile: '$(Build.ArtifactStagingDirectory)'
      #   #     Context: '/'
      #   #     ServerVersion: '7OrAbove'
        - task: ServiceNow-DevOps-Server-Job-Notification@1
          inputs:
            connectedServiceName: 'wiprocoelabdev-AzureCoeLab-ServiceNow DevOps Service Connection'
            Phase: 'COMPLETED'   

      - job: 'ProdDeploy'
        pool: #server
          name: DevopsAzure
          demands:
          - Agent.Version -equals 2.213.1

          vmImage: 'windows-latest'
        dependsOn: ChangeRequest
        condition: succeeded()  
        steps:
          - task: CopyFiles@2
            displayName: 'Copy WAR file Tomcat Server'
            inputs:
              SourceFolder: '$(Build.ArtifactStagingDirectory)'
              Contents: '**/*.war'
              TargetFolder: '/apache-tomcat-10.0.27/webapps/DevopsJava'
              CleanTargetFolder: true
              OverWrite: true
              
          # - task: CopyFiles@2
          #   inputs:
          #     SourceFolder: '$(Build.SourcesDirectory)'
          #     Contents: '**/*.war'
          #     TargetFolder: '/apache-tomcat-10.0.27/webapps/DevopsJava'
              

        # - task: Delay@1
        #   inputs:
        #     delayForMinutes: '0' 
  # - stage: 'Deploy'
  #   jobs:
    
# HTML
# Archive your static HTML project and save it with the build record.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml





    
